name: Docker Compose CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch submodules

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker images
      run: docker-compose build

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Run Tests
      run: |
        # Add your test commands here, e.g., check if services are running
        docker ps

    - name: Docker Compose Down
      run: docker-compose down
