name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      -name: Build and push the image
      -uses: actions/checkout@v2
      run: |
        docker login --username Ahmed-Bouzidia --pasword ${{secrets.TOKEN_DOCKER_REGISTRY}} ghcr.io
        docker build . -t  ghcr.io/Ahmed-Bouzidia/test-customer-api
        docker push  ghcr.io/Ahmed-Bouzidia/test-customer-api
