name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker login --username Ahmed-Bouzidia --password ${{ secrets.TOKEN_DOCKER_REGISTRY }} ghcr.io
          docker build . -t ghcr.io/ahmed-bouzidia/test-customer-api
          docker push ghcr.io/ahmed-bouzidia/test-customer-api 
